"""Updated Flashcard and FlashcardSet relationships

Revision ID: 0854e977cece
Revises: 359892d969ff
Create Date: 2023-04-13 12:32:35.293031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0854e977cece'
down_revision = '359892d969ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flashcard_set_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_flashcard_set_id', 'flashcard_set', ['flashcard_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_flashcard_set_id', type_='foreignkey')
        batch_op.drop_column('flashcard_set_id')

    # ### end Alembic commands ###
