"""Add correct and incorrect count to Flashcard

Revision ID: 2136cadfee22
Revises: 0854e977cece
Create Date: 2023-04-17 14:17:59.302947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2136cadfee22'
down_revision = '0854e977cece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('incorrect_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_column('incorrect_count')
        batch_op.drop_column('correct_count')

    # ### end Alembic commands ###
