"""Add flashcard sets

Revision ID: 359892d969ff
Revises: c3ac7ad5261a
Create Date: 2023-04-12 16:40:16.668541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359892d969ff'
down_revision = 'c3ac7ad5261a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard_set')
    # ### end Alembic commands ###
