"""Add image_url to StudyPodPost

Revision ID: 4be5fe9934c3
Revises: 996b6040e9d0
Create Date: 2024-02-21 16:54:53.207160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be5fe9934c3'
down_revision = '996b6040e9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_pod_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_pod_post', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
