"""Increase password_hash length

Revision ID: 598b2fbbd760
Revises: f7c7ef17aa65
Create Date: 2023-05-04 17:58:48.230263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598b2fbbd760'
down_revision = 'f7c7ef17aa65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
