"""File upload

Revision ID: ca8b73265bea
Revises: 7630a212c4cf
Create Date: 2024-02-15 16:20:11.794056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8b73265bea'
down_revision = '7630a212c4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_pod_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_pod_post', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
