"""Add public field to flashcard set

Revision ID: f7c7ef17aa65
Revises: 2136cadfee22
Create Date: 2023-04-19 09:43:16.854565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c7ef17aa65'
down_revision = '2136cadfee22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_column('public')

    # ### end Alembic commands ###
